language: r

dist: trusty
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python2.7
      - python-numpy

before_install:
  - R -e 'iinstall.packages("reticulate")'
  - R -e 'reticulate::py_install("shap")'

notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'


