sudo: required
language: r
warnings_are_errors: true
dist: trusty

# enable RELEASE_CANDIDATE to run (slow & fragile) tests of sampler validity before releases
env:
  global:
    - RELEASE_CANDIDATE=false
    - LINTR_COMMENT_BOT=false
    
r_packages:
  - reticulate
  - testthat
  - covr
  - knitr
  - rmarkdown

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - pip install --user numpy
  - pip install --user shap
  
notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'
  
  
