language: R
python:
  - "3.5"

sudo: required
dist: trusty
cache: packages

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -c conda-forge limix
  - pip install numpy
  - pip install --upgrade pip
  - pip install shap

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"

notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'
