language: R
cache: packages
sudo: required
dist: trusty

r:
  - oldrel
  - release
  - devel

env:
  global:
    - NOT_CRAN=true
  matrix:
    - PIP="pip" RETICULATE_PYTHON="/usr/bin/python"
    - PYTHON=3 PIP="pip3" RETICULATE_PYTHON="/usr/bin/python3"
    
before_install:
  - sudo apt-get -y install python${PYTHON}-pip python-dev python${PYTHON}-numpy
  - sudo $PIP install -U shap

notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'
  
  
