language: R
sudo: required
dist: trusty
cache: packages

before_install:
  - pip install numpy shap

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"

notifications:
  email: false

after_success:
  - Rscript -e 'covr::codecov()'
